.global start

start:
    // 0x00000000000000000000000000000082

    li %r6, 0x00
    stb %r6, 0(%r4)

    li %r6, 0x00
    stb %r6, 1(%r4)

    li %r6, 0x00
    stb %r6, 2(%r4)

    li %r6, 0x00
    stb %r6, 3(%r4)

    li %r6, 0x00
    stb %r6, 4(%r4)

    li %r6, 0x00
    stb %r6, 5(%r4)

    li %r6, 0x00
    stb %r6, 6(%r4)

    li %r6, 0x00
    stb %r6, 7(%r4)

    li %r6, 0x00
    stb %r6, 8(%r4)

    li %r6, 0x00
    stb %r6, 9(%r4)

    li %r6, 0x00
    stb %r6, 10(%r4)

    li %r6, 0x00
    stb %r6, 11(%r4)

    li %r6, 0x00
    stb %r6, 12(%r4)

    li %r6, 0x00
    stb %r6, 13(%r4)

    li %r6, 0x00
    stb %r6, 14(%r4)

    li %r6, 0x82
    stb %r6, 15(%r4)

    li %r3, 0
    blr